[package]
name = "vexide-startup"
version = "0.5.0"
edition =  "2024"
license = "MIT"
description = "User program startup and runtime support for vexide."
keywords = ["Robotics", "startup", "vex", "v5"]
categories = ["no-std", "science::robotics"]
repository = "https://github.com/vexide/vexide"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "Lewis McClelland <lewis@lewismcclelland.me>",
    "Tropical",
]

[dependencies]
bitflags = "2.4.2"
vexide-core = { workspace = true }
talc = { version = "4.3.1", optional = true }
compile-time = "0.2.0"

vex-sdk = { workspace = true }

[target.'cfg(not(target_os = "vexos"))'.dependencies]
vex-sdk-mock = { workspace = true, optional = true }

[target.'cfg(target_os = "vexos")'.dependencies]
vex-sdk-jumptable = { version = "0.1.0", optional = true }
vex-sdk-pros = { version = "0.0.1", optional = true }
vex-libunwind = { workspace = true, optional = true }
vex-libunwind-sys = { workspace = true, optional = true }

[build-dependencies]
vex-sdk-vexcode = { version = "0.0.1", optional = true }

[dev-dependencies]
vexide-devices = {  workspace = true }
vexide = { workspace = true, features = [
    "full",
    "vex-sdk-mock",
    "vex-sdk-jumptable",
] }

[lints]
workspace = true

[features]
allocator = ["dep:talc"]
panic-hook = []
abort-handler = []
backtrace = ["dep:vex-libunwind", "dep:vex-libunwind-sys"]

vex-sdk-jumptable = ["dep:vex-sdk-jumptable"]
vex-sdk-vexcode = ["dep:vex-sdk-vexcode"]
vex-sdk-pros = ["dep:vex-sdk-pros"]
vex-sdk-mock = ["dep:vex-sdk-mock"]

[package.metadata.docs.rs]
targets = ["armv7a-vex-v5"]
cargo-args = [
    "-Zbuild-std=std,panic_abort",
    "-Zbuild-std-features=compiler-builtins-mem",
]
