[package]
name = "vexide-startup"
version = "0.4.2-beta.1"
edition = "2021"
license = "MIT"
description = "Support code for V5 Brain user program booting"
keywords = ["Robotics", "startup", "vex", "v5"]
categories = ["no-std", "science::robotics"]
repository = "https://github.com/vexide/vexide"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical",
]

[dependencies]
bitflags = "2.4.2"
vex-sdk = { workspace = true }
vexide-core = { workspace = true }
compile-time = "0.2.0"

[lints]
workspace = true

[features]
default = []

[package.metadata.docs.rs]
targets = ["armv7a-none-eabi"] # Not actually, but this is at least close.
