[package]
name = "v5-debugger"
version = "0.1.0"
edition =  "2024"
license = "MIT"
description = "GDB remote stub for the VEX V5 Brain."
keywords = ["Robotics", "vex", "v5"]
authors = [
    "vexide",
    "Lewis McClelland <lewis@lewismcclelland.me>",
    "Tropical",
]
repository = "https://github.com/vexide/vexide"

[dependencies]
gdbstub = "0.7.8"
gdbstub_arch = "0.3.2"
vex-sdk = { workspace = true }
snafu.workspace = true
vexide-devices = { path = "../vexide-devices" }
zynq7000 = "0.1.1"
critical-section = "1.2.0"
bitbybit = "1.4.0"
arbitrary-int = "2.0.0"
derive-mmio = "0.6.1"
cortex-ar = "0.3.0"

[lints]
workspace = true
