[package]
name = "vexide-macro"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Proc macros for vexide"
keywords = ["Robotics", "bindings", "vex", "v5"]
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical",
]
repository = "https://github.com/vexide/vexide"

[dependencies]
proc-macro2 = "1.0.84"
quote = "1.0.35"
syn = { version = "^2.0.57", features = ["full"] }

[lib]
proc-macro = true

[lints]
workspace = true
